"""implemented_student_table.py

Revision ID: 6284f144fc2f
Revises: e46b6b0ae7a2
Create Date: 2022-11-20 11:54:20.940203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6284f144fc2f'
down_revision = 'e46b6b0ae7a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('first_name', sa.String(length=50), nullable=False))
    op.add_column('students', sa.Column('last_name', sa.String(length=50), nullable=False))
    op.add_column('students', sa.Column('pesel', sa.String(length=11), nullable=False))
    op.add_column('students', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('address', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'students', ['pesel'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'address')
    op.drop_column('students', 'phone')
    op.drop_column('students', 'pesel')
    op.drop_column('students', 'last_name')
    op.drop_column('students', 'first_name')
    # ### end Alembic commands ###
